version: "3.8"

services:
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: excalidraw
    ports:
      - "3922:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - /data/lhdisk-2tobn6g6/docker/excalidraw:/opt/node_app/app:delegated
      - /data/lhdisk-2tobn6g6/docker/excalidraw/package.json:/opt/node_app/package.json
      - /data/lhdisk-2tobn6g6/docker/excalidraw/yarn.lock:/opt/node_app/yarn.lock
      - /data/lhdisk-2tobn6g6/docker/excalidraw/notused:/opt/node_app/app/node_modules

volumes:
  notused:
